### PR TITLE
added more endpoints in wordlist

### PR DESCRIPTION
**Pull request by viralvaghela**

### CODE REVIEW

**Comment by viralvaghela** [comment]
#1

**Comment by Cyber-santhosh** [comment]
image

I get this results what can I do now to proceed.

**Comment by viralvaghela** [comment]
can you share the response from the server?

**Comment by viralvaghela** [comment]
seems like the response is not in the JSON format, and this tool is failing to parse the JSON Data

**Comment by Cyber-santhosh** [comment]
Then I can't use this tool right? or any solution.

**Comment by viralvaghela** [comment]
Let me check, if i can update something to handle all the cases!

**Pull request merged**
